### ISSUE TITLE
Does not commit

### ISSUE THREAD

**Issue by JustinTullgren** [commitizen/cz-jira-smart-commit#4]
Hello,

I am not able to commit with this adapter for commitizen.  I have used the `cz-conventional-changelog` adapter and that appears to work without issue.  We would like to switch to this adapter as we use Jira.  Any help would be appreciated.

Versions: cz-cli@2.8.2, cz-jira-smart-commit@1.0.3
Private module and repo.
Installed as dev dependency.
cz config path is local: `"path": "./node_modules/cz-jira-smart-commit"`

Steps to reproduce:
1. Edit file.
2. Stage file: `git stage -p` (interactive hunks) or `git add .`
3. Commit with cz: `git cz`
4. Add prompt responses (Jira ticket number, comments, etc)

**Expected**: A clean working tree with a commit message based upon prompt responses.
**Actual**: Dirty working tree that has staged edits and no commit has occured.

**Comment by JustinTullgren** [comment]
I looked at the current open [pull request](https://github.com/commitizen/cz-jira-smart-commit/pull/3) and that is the problem.  This can be closed when that PR is resolved.  

Thanks!

**Comment by f0rr0** [comment]
I'm still seeing this issue

**Comment by wcalebgray** [comment]
I'm also still seeing this issue

**Comment by pekhota** [comment]
I'm also still seeing this issue
