### ISSUE TITLE
When using cz-jira-smart-commit no commit is generated

### ISSUE THREAD

**Issue by pgoodjohn** [commitizen/cz-jira-smart-commit#8]
I just downloaded `Commitizen` and `cz-jira-smart-commit` to implement them in our internal projects but I can't seem to get the latter to work.

When I run `git cz` I get the correct prompt (i.e. GitHub commit message, Jira Issude Id, Workflow command etc) but after filling them all in no commit is generated and the files remain in staging without being actually committed to the project.

I tried with both packages installed locally and globally but no chance, using any other wrapper (i.e. `cz-conventional-changelog`) everything works flawlessy. Any idea what could be causing the JIRA wrapper not to be working correctly?

My `.cz.json` looks like the following:

    {
       "path": "node_modules/cz-jira-smart-commit"
    }

**Comment by pgoodjohn** [comment]
#9 Fixes this issue.

**Comment by jimthedev** [comment]
Hi thanks for the PR. Can you make sure that it isn't pointing to github and is instead pointing to the npm package?  

See this line: https://github.com/commitizen/cz-jira-smart-commit/pull/9/files#diff-3fbb47e318cd8802bd325e7da9aaabe8R5

**Comment by pgoodjohn** [comment]
Hi @jimthedev!

e2e1d234f4778890f47fc2c9ef017bceb319ba6e points to npm package.
Sorry for not noticing but we needed to use the fixed package internally and I forgot to change it before submitting the PR
